In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [ ]:
import sys

sys.getsizeof(python_list[0]) * len(python_list)

2400

In [ ]:
nump_array = np.arange(100)
nump_array[:5]

array([0, 1, 2, 3, 4])

In [9]:
nump_array.nbytes

800

In [11]:
l1 = [1, 2, 3]
l2 = [8, 7, 9]

# zip(l1,l2)
# tuple(zip(l1,l2))
for x, y in zip(l1, l2):
    print(x, y)

1 8
2 7
3 9


In [13]:
SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()

print("Python list took: ",end_time-start_time)

Python list took:  0.08475804328918457


In [14]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:4],n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [15]:
start_time = time.time()
n3 = n1+n2
end_time = time.time()

print("Numpy array took: ",end_time-start_time)

Numpy array took:  0.005390644073486328
