In [ ]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
b[1, 2]

np.int64(6)

In [ ]:
b[-1, 0:2]

array([7, 8])

In [ ]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
# Customer ID, Name
c = np.array([[101, "Mira"], [102, "Abdul"], [103, "Andrea"]])
# Customer Id, Purchase Amount, Purchase Date
d = np.array(
    [
        [101, 250.50, "2023-08-01"],
        [102, 150.00, "2023-08-02"],
        [103, 300.75, "2023-08-01"],
    ]
)

In [ ]:
np.hstack((c, d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [ ]:
e = np.array(
    [
        [104, "Venkat"],
        [105, "John"],
        [106, "Kathy"],
    ]
)

In [ ]:
np.vstack((c, e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [ ]:
transactions = np.array(
    [
        [101, "Mohan", 250.50, "2023-08-01"],
        [102, "Bob", 150.00, "2023-08-02"],
        [103, "Fatima", 300.75, "2023-08-01"],
        [104, "David", 400.20, "2023-08-03"],
        [105, "Aryan", 330.1, "2023-08-04"],
    ]
)

a, b = np.hsplit(transactions, [2])

In [24]:
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [26]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [28]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [29]:
monthly_sales[result]

array([30, 28])

In [32]:
index = np.argmax(monthly_sales)
index

np.int64(4)

In [34]:
monthly_sales[index]

np.int64(42)

In [36]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [ ]:
transactions[:, 2]

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [ ]:
transactions[:, 2].astype(float)

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [43]:
index = np.argmax(transactions[:, 2].astype(float))
index


np.int64(3)