In [1]:
import numpy as np

In [ ]:
revenue_quater1=np.array([10,12,9])
# revenue_quater1.ndim #number of dimensions
revenue_quater1

array([10, 12,  9])

In [5]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim

2

In [7]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [10]:
rev[1,0] #getting the value of 2nd array's 1st num

np.int64(15)

In [12]:
rev[1,0]=14
rev

array([[10, 12,  9],
       [14, 11, 13]])